import {test} from 'node:test';import assert from 'node:assert/strict';import {Flight,stageFor,cleanSave} from '../dist/game.js';
test('35-second cargo deadline rejects late clicks and awards credits exactly once',()=>{const f=new Flight();f.start(100);assert.equal(f.click(100),true);f.click(35099);assert.equal(f.click(35100),false);assert.equal(f.score,2);assert.equal(f.save.credits,2);f.finish();f.tick(40000);assert.equal(f.save.credits,2);});
test('five stages transition exactly at thresholds',()=>{assert.deepEqual([0,69,70,179,180,349,350,599,600,9000].map(stageFor),[0,0,1,1,2,2,3,3,4,4]);});
test('ship purchases subtract price once and multiply points, never raw clicks',()=>{const f=new Flight({credits:300});assert.equal(f.equip('pulse').ok,true);assert.equal(f.save.credits,0);assert.equal(f.equip('pulse').ok,true);f.start(0);f.click(50);assert.equal(f.score,2);assert.equal(f.clicks,1);assert.equal(f.cps(50),1);assert.equal(f.equip('scout').ok,false);f.tick(30000);assert.equal(f.save.credits,2);});
test('insufficient funds and invalid ships leave state intact',()=>{const f=new Flight({credits:299});assert.equal(f.equip('pulse').ok,false);assert.equal(f.equip('unknown').ok,false);assert.equal(f.save.credits,299);assert.equal(f.ship.id,'scout');});
test('new runs reset score, retain wallet, and repeated starts do not extend time',()=>{const f=new Flight();f.start(0);f.click(5);assert.equal(f.start(5000),false);assert.equal(f.deadline,35000);f.tick(35000);f.start(40000);assert.equal(f.score,0);assert.equal(f.save.credits,1);assert.equal(f.remaining(40000),35);});
test('stale click samples expire and malformed saves are sanitized',()=>{const f=new Flight();f.start(0);f.click(10);assert.equal(f.cps(1010),0);assert.equal(cleanSave({credits:-1,selected:'zenith',owned:[]}).selected,'scout');assert.equal(cleanSave({credits:NaN}).credits,0);});

test('stealth trades flight time for speed and keeps the selected ship locked during flight',()=>{const f=new Flight({owned:['spectre'],selected:'spectre'});assert.equal(f.remaining(0),12);f.start(100);f.click(101);assert.equal(f.score,5);assert.equal(f.equip('scout').ok,false);assert.equal(f.click(12099),true);assert.equal(f.click(12100),false);assert.equal(f.save.credits,10);assert.equal(f.remaining(12100),0);f.equip('scout');f.start(20000);assert.equal(f.remaining(20000),35);});
